services:
  - type: web
    name: cityops-backend
    runtime: node
    buildCommand: cd cityops-backend && npm install && npx prisma generate
    startCommand: cd cityops-backend && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
